CLDN-1045 Pipeline for superset-ui
CybercentreCanada/superset-ui pull request #18
Opened 2021-11-01 20:20 UTC by cccs-nik

2021-11-02 21:42 UTC, cccs-tom requested changes

2021-11-02 21:42 UTC, cccs-tom commented on azure-pipelines.yml
> +      - feature/CLDN-*
In general, we don't include feature branches in the trigger. All PRs will be automatically built, so when devs are ready to build they can create a PR.

2021-11-02 21:42 UTC, cccs-tom commented on azure-pipelines.yml
> +        workingDirs: [
This JSON-style list is kind of weird in a YAML file. Can it be converted to YAML?

2021-11-02 21:42 UTC, cccs-tom commented on azure-pipelines.yml
> +  vmImage: 'ubuntu-latest'
I'm a big fan of using quotes only when they're required in YAML
```suggestion
  vmImage: ubuntu-latest
```

2021-11-02 21:42 UTC, cccs-tom commented on azure-pipelines.yml
> +  tag: '$(Build.BuildId)'
```suggestion
  tag: $(Build.BuildId)
```

2021-11-02 21:42 UTC, cccs-tom commented on azure-pipelines.yml
> +        versionSpec: '14.x'
```suggestion
        versionSpec: 14.x
```

2021-11-03 17:23 UTC, cccs-tom approved these changes

2021-11-05 14:12 UTC, cccs-RyanS approved these changes

2021-11-08 16:40 UTC, merged